I assume coding is defficult , i dont know , me only or all the people terminal use is hard to me or vitiul stedio. I don't know is my laptop or evry one have these proplam
githup too may be is not dum people play ground,
